### Registering a new user
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "fullName": "Test Student",
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Upload a resource
POST http://127.0.0.1:5000/resources/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="userID"

1
--boundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< D:\Pictures\Screenshots\Screenshot 2026-08-13 0517544.png
--boundary--

### Search
POST http://127.0.0.1:5000/search
Content-Type: application/json

{
  "query": "customer order process"
}

### List categories
GET http://127.0.0.1:5000/categories

### Create a new category
POST http://127.0.0.1:5000/categories
Content-Type: application/json

{
  "categoryName": "Nursing & Healthcare",
  "description": "Nursing and healthcare: patient care, clinical practice, medical procedures, healthcare systems"
}